autograder/urls.py
# Django imports
from django.contrib import admin, auth
from django.urls import include, path
from django.views.generic import TemplateView

# Local imports
from .views import *
from .forms import StudentLoginForm

urlpatterns = [
	path('', Home.as_view(), name='home'),
    path('faq/', TemplateView.as_view(template_name='autograder/faq.html'), name='faq'),
    path('admin/', admin.site.urls),
    path('courses/', CourseListView.as_view(), name='course_list'),
    path('courses/create/', CourseCreateView.as_view(), name='create_course'),
    path('courses/<int:pk>/', CourseView.as_view(), name='view_course'),
    path('courses/<int:pk>/delete/', CourseDeleteView.as_view(), name='delete_course'),
    path('assignments/create/', AssignmentCreateView.as_view(), name='create_assignment'),
    path('assignments/<int:pk>/', AssignmentView.as_view(), name='view_assignment'),
    path('assignments/<int:pk>/delete/', AssignmentDeleteView.as_view(), name='delete_assignment'),
    path('assignments/<int:pk>/submissions', AssignmentSubmissionListView.as_view(), name='view_assignment_submissions'),
    path('test-cases/create/', TestCaseCreateView.as_view(), name='create_testcase'),
    path('test-cases/<int:pk>/', TestCaseView.as_view(), name='view_testcase'),
    path('test-cases/<int:pk>/delete/', TestCaseDeleteView.as_view(), name='delete_testcase'),
    path('assignments/<int:pk>/upload/', SubmissionCreateView.as_view(), name='create_submission'),
    path('submissions/<int:pk>/', SubmissionView.as_view(), name='view_submission'),
    path('submissions/<int:pk>/confirm/', SubmissionConfirmView.as_view(), name='confirm_submission'),
    path('submissions/<int:pk>/cancel/', SubmissionDeleteView.as_view(), name='delete_submission'),
    path('submissions/<int:pk>/download/', SubmissionDownloadView.as_view(), name='download_submission'),
    path('submissions/recent/', SubmissionRecentListView.as_view(), name='recent_submissions_list'),
    path('login/', auth.views.LoginView.as_view(template_name='autograder/student_login.html', authentication_form=StudentLoginForm), name='student_login'),
    path('logout/', auth.views.LogoutView.as_view(), name='logout'),
    path('staff-login/', auth.views.LoginView.as_view(template_name='autograder/staff_login.html'), name='staff_login'),
    path('students/', StudentListView.as_view(), name='list_students'),
    path('students/register/', StudentCreateView.as_view(), name='create_student'),
    path('students/register-bulk/', StudentBulkCreateView.as_view(), name='bulk_create_student'),
    path('students/<str:username>/', StudentView.as_view(), name='view_student'),
    path('students/<str:username>/delete', StudentDeleteView.as_view(), name='delete_student'),
    path('students/<str:username>/enroll', StudentEnrollView.as_view(), name='enroll_student'),
    path('students/<str:username>/unenroll', StudentUnenrollView.as_view(), name='unenroll_student')
]

autograder/models.py
# Standard imports
from datetime import datetime
import os
import shutil
import subprocess

# Django imports
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.models import AbstractUser
from django.db import models, transaction
from django.dispatch.dispatcher import receiver
from django.urls import reverse_lazy

# Docker import
import docker


class AutograderUser(AbstractUser):

    def __str__(self):
        return self.get_full_name()

    @admin.display(description='Gav ID')
    def admin_gav_id_display(self):
        return f'G00 {self.username}' if not self.is_staff else None

    # Staff accounts = instructors
    # Non-staff accounts = students


class Course(models.Model):

    title = models.CharField(max_length=100)

    students = models.ManyToManyField(AutograderUser)

    def __str__(self):
        return self.title
    
    def build_absolute_url(self):
        return reverse_lazy('view_course', args=[self.id])
    

class Assignment(models.Model):

    title = models.CharField(max_length=280)

    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
    def build_absolute_url(self):
        return reverse_lazy('view_assignment', args=[self.id])
    
    def get_absolute_url(self):
        return self.build_absolute_url()


class TestCase(models.Model):

    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)

    input = models.TextField(blank=True)
    output = models.TextField(blank=True)

    def __str__(self):
        return f'Test Case for {self.assignment.title}'

# When a test case is updated, delete its test outputs so tests are re-run with the updated test case
@receiver(models.signals.pre_save, sender=TestCase)
def delete_obsolete_testoutputs(sender, instance, **kwargs):

    # Not necessary when test case is created
    if instance._state.adding:
        return
    
    # NOTE: This will not call the delete() method of any TestOutput objects,
        #   so if TestOutput.delete() is overridden in the future, then change this.
    transaction.on_commit(lambda: TestOutput.objects.filter(testcase=instance).delete())


def submission_path(instance, filename):
    return os.path.join(
        'student-files',
        str(instance.student.username),
        str(instance.assignment.id),
        datetime.now().strftime('%Y-%m-%d-%H%M%S'),
        filename
    )


class Submission(models.Model):
    
    student = models.ForeignKey(AutograderUser, on_delete=models.CASCADE)
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)

    date = models.DateTimeField(auto_now=True)
    confirmed = models.BooleanField(default=False)

    source_file = models.FileField(upload_to=submission_path)

    compiles = models.BooleanField(default=False)

    def __str__(self):
        return f'Submission from {self.student} for {self.assignment}'
    
    def build_absolute_url(self):
        return reverse_lazy('view_submission', args=[self.id])
    
    def get_absolute_url(self):
        return self.build_absolute_url()

    def build_download_url(self):
        return reverse_lazy('download_submission', args=[self.id])

    def get_context_path(self):
        return os.path.join(settings.MEDIA_ROOT, 'docker', f'context-{self.pk}')

    def docker_prep(self, client):

        # Create context directory, including intermediate directories if necessary
        context_path = self.get_context_path()
        os.makedirs(context_path)

        # Attempt to compile
        try:
            arg_list = ['g++', '-o', os.path.join(context_path, 'student-program'), self.source_file.path]
            subprocess.check_call(arg_list, timeout=2)
        except:
            # Destroy context if compilation fails
            shutil.rmtree(context_path)
            return None
        
        # Copy Dockerfile to context
        shutil.copy(os.path.join(settings.BASE_DIR, 'Dockerfile'), context_path)

        # Create input files in context
        for testcase in self.assignment.testcase_set.all():
            with open(os.path.join(context_path, f'input-file-{testcase.pk}.txt'), 'w') as input_file:
                input_file.write(testcase.input)

        # Build image
        image_tag = f'gav-autograder/submission-{self.pk}'
        client.images.build(path=context_path, tag=image_tag)

        return image_tag

    def full_test(self):

        # Remove old TestOutputs
        # NOTE: This will not call the delete() method of any TestOutput objects,
        #   so if TestOutput.delete() is overridden in the future, then change this.
        TestOutput.objects.filter(submission=self).delete()

        # Get docker client
        docker_client = docker.from_env()

        # Create docker context and image
        image_tag = self.docker_prep(docker_client)

        # Run tests if prep succeeded
        if image_tag is not None:
            
            for testcase in self.assignment.testcase_set.all():
                self.single_test(docker_client, image_tag, testcase)
        
            # Remove docker context and image
            self.docker_cleanup(docker_client, image_tag)

        return (image_tag is not None)

    def single_test(self, client, image_tag, testcase):

        # Create
        container = client.containers.create(
            image_tag,
            command=f'bash -c "./student-program < input-file-{testcase.pk}.txt"',
            cpu_shares=512,
            cpuset_cpus='0',
            mem_limit='500m',
            network_disabled=True,
            read_only=True,
            security_opt=['no-new-privileges'],
            version='auto'
        )
        # Start
        container.start()
        # Wait
        container.wait(timeout=5)
        # Get Logs
        container_output = container.logs().decode()
        # Remove
        container.remove()

        # Create TestOutput object
        TestOutput.objects.create(
            submission=self,
            testcase=testcase,
            output=container_output
        )

        return container_output

    def docker_cleanup(self, client, image_tag):
        
        # Remove image
        client.images.remove(image_tag)

        # Delete context directory
        shutil.rmtree(self.get_context_path())

    def save(self, *args, **kwargs):

        # Save normally, ensure source_file exists
        super().save(*args, **kwargs)

        # Unless otherwise specified, run all tests
        if kwargs.get('run_tests', True):

            # Set compiles flag if program compiles
            self.compiles = self.full_test()

            # Save changes
            super().save(update_fields=['compiles'])

    @property
    def test_results(self):

        results = {'compiles': self.compiles, 'tests': []}

        # No need to continue if program doesn't compile
        if not self._state.adding and not self.compiles:
            return results
        
        docker_client = None
        image_tag = None

        for testcase in self.assignment.testcase_set.all():

            try:
                test_output = self.testoutput_set.get(testcase=testcase).output
            
            except TestOutput.DoesNotExist:

                if docker_client is None:
                    docker_client = docker.from_env()
                    image_tag = self.docker_prep(docker_client)
                
                test_output = self.single_test(docker_client, image_tag, testcase)
            
            result = {
                # Required for calculating grade
                'passed': test_output == testcase.output,
                # Required for display on submission page
                'input': testcase.input,
                'output': [
                    {
                        'char': test_output[i],
                        'incorrect': (i >= len(testcase.output)) or (test_output[i] != testcase.output[i]),
                        'newline': (test_output[i] == '\n')
                    }
                    for i in range(len(test_output))
                ],
                'missing_output': len(testcase.output) - len(test_output)
            }
            
            results['tests'].append(result)
        
        if docker_client is not None:
            self.docker_cleanup(docker_client, image_tag)

        return results

    def delete_source_file_directory(self, directory):
        top_directory = os.path.join(settings.MEDIA_ROOT, 'student-files')
        # Ensure directory is empty before deleting it to prevent accidental deletions
        while directory != top_directory and not os.listdir(directory):
            os.rmdir(directory)
            directory = os.path.dirname(directory)

    # Deletes source_file and its parent directory, if empty
    def delete_source_file(self):
        path = self.source_file.path
        if os.path.exists(path):
            self.source_file.delete(False)
            self.delete_source_file_directory(os.path.dirname(path))

# When a submission's student, assignment, or source_file field is updated,
#   move/delete the old source_file
@receiver(models.signals.pre_save, sender=Submission, weak=False)
def move_or_delete_submission_file(sender, instance, **kwargs):

    if instance._state.adding or kwargs.get('update_fields', None) is None:
        return

    if 'source_file' in kwargs['update_fields']:

        # Retrieve old submission instance
        old_submission = Submission.objects.get(pk=instance.pk)

        # Delete old source file
        transaction.on_commit(lambda: old_submission.delete_source_file())

    elif 'student' in kwargs['update_fields'] or 'assignment' in kwargs['update_fields']:

        # Take note of old (absolute) path
        old_path = instance.source_file.path

        # Create new file name (and relative path)
        new_name = submission_path(instance, os.path.basename(old_path))

        def move_submission_file():

templates/autograder/assignment.html
{% extends 'base.html' %}
{% block title %} - {{ object }}{% endblock %}
{% block header %}<h1>{{ object }}</h1>{% endblock %}
{% block content %}
<p>From <a href="{% url 'view_course' object.course.pk %}">{{ object.course }}</a></p>
<h2><u>Test Cases</u></h2>
{% if user.is_staff %}
<table>
    <thead>
        <tr>
            <td>Test Case</td>
            <td>Staff Actions</td>
        </tr>
    </thead>
    <tbody>
        {% for testcase in object.testcase_set.all %}
        <tr>
            <td><a href="{% url 'view_testcase' testcase.pk %}">Test Case #{{ testcase.pk }}</a></td>
            <td><a href="{% url 'delete_testcase' testcase.pk %}">Delete</a></td>
        </tr>
        {% empty %}
        <tr><td colspan="2">This assignment has no test cases.</td></tr>
        {% endfor %}
    </tbody>
</table>
<br>
<h3><u>Staff Actions</u></h3>
<ul>
    <li><a href="{% url 'view_assignment_submissions' object.pk %}">View Submissions</a></li>
    <li><a href="{% url 'create_testcase' %}?assignment={{ object.id }}">Create Test Case</a></li>
</ul>
{% else %}
    {% if object.testcase_set.all %}
        <ol>
            {% for testcase in object.testcase_set.all %}
            <li><a href="{% url 'view_testcase' testcase.pk %}">Test Case</a></li>
            {% endfor %}
        </ol>
    {% else %}
        <p>No test cases are currently available.</p>
    {% endif %}
    <h2><u>Your Submissions</u></h2>
    {% if user_submissions|length < 10 and not user_has_unconfirmed_submission %}
        <p><a href="{% url 'create_submission' object.pk %}">Upload a new submission</a></p>
    {% endif %}
    {% ifequal user_submissions|length 10 %}
        <p>You have reached the maximum number of submissions permitted for this assignment.</p>
    {% endifequal %}
    <ul>
        {% for submission in user_submissions %}
            <li>
                <a href="{% url 'view_submission' submission.pk %}">
                    {% if submission.confirmed %}
                        Submission {{ forloop.revcounter }} - {{ submission.date }}
                    {% else %}
                        Unconfirmed submission
                    {% endif %}
                </a>
            </li>
        {% empty %}
            <li>No submissions</li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock %}

templates/autograder/course.html
{% extends 'base.html' %}
{% block title %} - {{ object }}{% endblock %}
{% block header %}<h1>{{ object }}</h1>{% endblock %}
{% block content %}
<h2><u>Assignments</u></h2>
<table>
    <thead>
        <tr>
            <th>Assignment</th>
            {% if user.is_staff %}
            <th>Staff Actions</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for assignment in assignment_set %}
        <tr>
            <td><a href="{% url 'view_assignment' assignment.pk %}">{{ assignment }}</a></td>
            {% if user.is_staff %}
                <td><a href="{% url 'delete_assignment' assignment.pk %}">Delete</a></td>
            {% endif %}
        </tr>
        {% empty %}
        <tr><td colspan="2">No assignments are available at this time</td></tr>
        {% endfor %}
    </tbody>
</table>
{% if user.is_staff %}
    <br>
    <h3><u>Staff Actions</u></h3>
    <ul>
        <li><a href="{% url 'create_assignment' %}?course={{ object.id }}">Create Assignment</a></li>
    </ul>
{% endif %}
{% endblock %}

templates/autograder/index.html
{% extends 'base.html' %}
{% block content %}
	Welcome, {% if user.is_authenticated %}{{ user.get_full_name }}{% else %}Anonymous User{% endif %}
	<br>
	{% if user.is_authenticated %}
		<h3><u>Quick Access</u></h3>
	{% endif %}
	{% if user.is_staff %}
		<ul>
			<li><a href="{% url 'recent_submissions_list' %}">Recent Submissions</a></li>
			<li><a href="{% url 'list_students' %}">Manage Students</a></li>
		</ul>
	{% elif user.is_authenticated %}
		<ul>
			<li>View <a href="{% url 'course_list' %}">Courses</a> you are enrolled in</li>
			<li>Upload & submit programs for your assignments</li>
		</ul>
	{% else %}
		<p>You may view a list of <a href="{% url 'course_list' %}">Courses</a>, but will need to <a href="{% url 'student_login' %}">log in</a> to access most features</p>
	{% endif %}
{% endblock %}

templates/autograder/student_delete.html
{% extends 'base.html' %}
{% block title %} - Delete Student{% endblock %}
{% block header %}<h1>Delete {{ object }} (G00 {{ object.username }})</h1>{% endblock %}
{% block content %}
<p>Confirm your deletion of this student.</p>
<p><b>This will delete all of this student's submissions and test results.</b></p>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Delete</button>
</form>
{% endblock %}

templates/autograder/student_list.html
{% extends 'base.html' %}
{% block title %} - Students{% endblock %}
{% block header %}<h1>Students</h1>{% endblock %}
{% block content %}
<table class="paged-table">
    <thead>
        <tr>
            <th>Gavilan ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for student in object_list %}
        <tr>
            <td><a href="{% url 'view_student' student.username %}">G00 {{ student.username }}</a></td>
            <td>{{ student.first_name }}</td>
            <td>{{ student.last_name }}</td>
            <td><a href="{% url 'delete_student' student.username %}">Delete</a></td>
        </tr>
        {% empty %}
        <tr><td span="4">No students to display</td></tr>
        {% endfor %}
    </tbody>
</table>
<br>
<h3><u>Register Students</u></h3>
<ul>
    <li><a href="{% url 'create_student' %}">Register a student</a></li>
    <li><a href="{% url 'bulk_create_student' %}">Register students in bulk</a></li>
</ul>
{% endblock %}
{% load static %}
{% block scripts %}
	<script type="text/javascript" charset="utf-8" src="{% static 'table_script.js' %}"></script>
{% endblock %}

templates/autograder/student_register.html
{% extends 'base.html' %}
{% block title %} - Register Student{% endblock %}
{% block content %}
<form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Register</button>
</form>
{% endblock %}

templates/autograder/student_register_bulk.html
{% extends 'base.html' %}
{% block title %} - Bulk Register Students{% endblock %}
{% block header %}<h1>Bulk Register Students</h1>{% endblock %}
{% block content %}
<form enctype="multipart/form-data" method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <p>
        Each line should be of the format: gav-id,first-name,last-name<br>
        Ex. 123456,John,Smith
    </p>
    <button>Register</button>
</form>
{% endblock %}

templates/autograder/student_unenroll.html
{% extends 'base.html' %}
{% block title %} - Unenroll Student{% endblock %}
{% block header %}<h1>Unenroll {{ object.get_full_name }}</h1>{% endblock %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Unenroll</button>
</form>
{% endblock %}

templates/autograder/submission_confirm.html
{% extends 'base.html' %}
{% block title %} - Confirm Submission{% endblock %}
{% block header %}<h1>Confirm Submission?</h1>{% endblock %}
{% block content %}
<p>You cannot delete a submission after it has been confirmed, but you may make further submissions.</p>
<form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Yes, Confirm</button>
</form>
{% endblock %}

templates/autograder/submission_list.html
{% extends 'base.html' %}
{% load autograder_filters %}
{% block title %} - Submissions{% endblock %}
{% block header %}<h1>Submissions for {{ assignment.title }}</h1>{% endblock %}
{% block content %}
<form autocomplete="off">
    <input type="checkbox" id="check-include-unconfirmed"> Include Unconfirmed Submissions
</form>
<table class="paged-table">
    <thead>
        <tr>
            <th>Student</th>
            <th>Status</th>
            <th>Grade</th>
            <th>Date/Time</th>
            <th>Link</th>
        </tr>
    </thead>
    <tbody>
        {% for submission in object_list %}
        <tr>
            <td><a href="{% url 'view_student' submission.student.username %}">{{ submission.student.get_full_name }} (G00 {{ submission.student.username }})</a></td>
            <td>{% if submission.confirmed %}Confirmed{% else %}Unconfirmed{% endif %}</td>
            <td>{{ submission|submissiongrade }}</td>
            <td>{{ submission.date }}</td>
            <td><a href="{% url 'view_submission' submission.pk %}">View</a></td>            
        </tr>
        {% empty %}
        <tr><td colspan="5">No submissions exist for this assignment</td></tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}
{% load static %}
{% block scripts %}
	<script type="text/javascript" charset="utf-8" src="{% static 'table_script.js' %}"></script>
{% endblock %}

templates/autograder/submission_recent_list.html
{% extends 'base.html' %}
{% load autograder_filters %}
{% block title %} - Recent Submissions{% endblock %}
{% block header %}<h1>Recent Submissions</h1>{% endblock %}
{% block content %}
<form autocomplete="off">
    <input type="checkbox" id="check-include-unconfirmed"> Include Unconfirmed Submissions
</form>
<table class="non-paged-table">
    <thead>
        <tr>
            <th>Assignment</th>
            <th>Course</th>
            <th>Student</th>
            <th>Status</th>
            <th>Grade</th>
            <th>Date/Time</th>
            <th>Link</th>
        </tr>
    </thead>
    <tbody>
        {% for submission in object_list %}
        <tr>
            <td><a href="{% url 'view_assignment' submission.assignment.pk %}">{{ submission.assignment }}</a></td>
            <td><a href="{% url 'view_course' submission.assignment.course.pk %}">{{ submission.assignment.course }}</a></td>
            <td><a href="{% url 'view_student' submission.student.username %}">{{ submission.student.get_full_name }}<br>(G00 {{ submission.student.username }})</a></td>
            <td>{% if submission.confirmed %}Confirmed{% else %}Unconfirmed{% endif %}</td>
            <td>{{ submission|submissiongrade }}</td>
            <td>{{ submission.date }}</td>
            <td><a href="{% url 'view_submission' submission.pk %}">View</a></td>
        </tr>
        {% empty %}
        <tr><td colspan="5">No submissions exist</td></tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}
{% load static %}
{% block scripts %}
	<script type="text/javascript" charset="utf-8" src="{% static 'table_script.js' %}"></script>
{% endblock %}

templates/autograder/submission_upload.html
{% extends 'base.html' %}
{% block title %} - Upload Submission{% endblock %}
{% block header %}<h1>Upload Assignment Submission</h1>{% endblock %}
{% block content %}
<p>For: <a href="{% url 'view_assignment' assignment.id %}">{{ assignment }}</a></p>
<p>You can view your results before confirming or cancelling your submission.</p>
<form enctype="multipart/form-data" method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Upload</button>
</form>
{% endblock %}

templates/autograder/test_results.html
<div>
    {% if test_results.compiles %}
    {% for test in test_results.tests %}
    <div>
        <h3>Test {{ forloop.counter }}: {% if test.passed %}PASSED{% else %}FAILED{% endif %}</h3>
        <h5>Input:</h5>
        <div>{{ test.input }}</div>
        <h5>Output:</h5>
        <div>
            {% for char in test.output %}<span class="feedback-{% if char.incorrect %}incorrect{% else %}correct{% endif %}{% if char.newline %} feedback-newline">\n<br>{% else %}">{% ifequal char.char ' ' %}&nbsp;{% else %}{{ char.char }}{% endifequal %}{% endif %}</span>{% endfor %}{% if test.missing_output > 0 %}<br><span class="missing-output-message">({{ test.missing_output }} characters missing)</span>{% endif %}
        </div>
    </div>
    {% endfor %}
    {% else %}
    <p>Compilation failed or timed out. No test results to report.</p>
    {% endif %}
</div>

templates/autograder/testcase_delete.html
{% extends 'base.html' %}
{% block title %} - Delete Test Case{% endblock %}
{% block header %}<h1>Delete Test Case #{{ object.pk }}</h1>{% endblock %}
{% block content %}
<p>Confirm your deletion of this test case.</p>
<p><b>This will delete all test outputs associated with this test case.</b></p>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Delete</button>
</form>
{% endblock %}